### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by Hyleus** [TheWiseNoob/OpenMusicPlayer#3]
Currently there are many issues with your formatting:
- Spaces around the dot operator, this wastes horizontal space for no good reason.
- Spaces around the arrow operator, this wastes horizontal space for no good reason.
- Empty lines between code, this wastes vertical space for no good reason. Consider using it only if it really needs a break.

Consider addressing this points. You should enforce a good code style like for example: https://users.ece.cmu.edu/~eno/coding/CppCodingStandard.html

**Comment by TheWiseNoob** [comment]
The reason, for me, is that extra space me it far more readable for me.
